# Generated by Django 5.1.6 on 2025-04-27 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="response",
        ),
        migrations.RemoveField(
            model_name="response",
            name="form",
        ),
        migrations.AddField(
            model_name="response",
            name="report",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="report.report",
            ),
            preserve_default=False,
        ),
    ]
