# Generated by Django 5.1.6 on 2025-04-18 07:46

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExtensionReport",
            fields=[
                (
                    "report_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reports.report",
                    ),
                ),
                ("components", models.TextField()),
                ("scope", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("target_beneficiary_group", models.CharField(max_length=255)),
                ("tbg_served", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "source_of_funding",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            bases=("reports.report",),
        ),
        migrations.CreateModel(
            name="OtherResearchReport",
            fields=[
                (
                    "report_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reports.report",
                    ),
                ),
                ("output_title", models.CharField(max_length=255)),
                ("output_type", models.CharField(max_length=100)),
                ("public_event_type", models.CharField(max_length=100)),
                ("event_title", models.CharField(max_length=255)),
                ("organizer_name", models.CharField(max_length=255)),
                ("event_venue", models.CharField(max_length=255)),
                ("event_location", models.CharField(max_length=255)),
                ("event_start_date", models.DateField()),
                ("event_end_date", models.DateField()),
                ("output_firstshownorreleasedtopublic_date", models.DateField()),
                ("industry_utilization", models.TextField(blank=True, null=True)),
            ],
            bases=("reports.report",),
        ),
        migrations.CreateModel(
            name="OthersReport",
            fields=[
                (
                    "report_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reports.report",
                    ),
                ),
                ("description", models.TextField()),
            ],
            bases=("reports.report",),
        ),
        migrations.CreateModel(
            name="PaperPresentationReport",
            fields=[
                (
                    "report_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reports.report",
                    ),
                ),
                ("research_title", models.CharField(max_length=255)),
                ("presented_paper_title", models.CharField(max_length=255)),
                ("presentation_type", models.CharField(max_length=100)),
                ("conference_title", models.CharField(max_length=255)),
                ("organizer_name", models.CharField(max_length=255)),
                ("conference_location", models.CharField(max_length=255)),
                ("venue", models.CharField(max_length=255)),
                ("conference_start_date", models.DateField()),
                ("conference_end_date", models.DateField()),
                ("presentation_date", models.DateField()),
            ],
            bases=("reports.report",),
        ),
        migrations.CreateModel(
            name="PartnershipReport",
            fields=[
                (
                    "report_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reports.report",
                    ),
                ),
                (
                    "type_of_extension_activities_under_this_partnership",
                    models.CharField(max_length=255),
                ),
                ("extension_partnership_title", models.CharField(max_length=255)),
                ("up_scope_of_work", models.TextField()),
                ("partner_stakeholder_name", models.CharField(max_length=255)),
                ("stakeholder_category", models.CharField(max_length=100)),
                ("partnership_agreement_type", models.CharField(max_length=100)),
                ("partnership_agreement_effectivity_start_date", models.DateField()),
                (
                    "partnership_agreement_effectivity_end_date",
                    models.DateField(blank=True, null=True),
                ),
            ],
            bases=("reports.report",),
        ),
        migrations.CreateModel(
            name="PatentReport",
            fields=[
                (
                    "report_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reports.report",
                    ),
                ),
                ("patent_title", models.CharField(max_length=255)),
                ("patent_type", models.CharField(max_length=100)),
                ("application_no", models.CharField(max_length=100)),
                ("inventors_name", models.TextField()),
                ("owner_name", models.CharField(max_length=255)),
                (
                    "application_publication_date",
                    models.DateField(blank=True, null=True),
                ),
                ("patent_grant_date", models.DateField(blank=True, null=True)),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "commerical_product_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("industry_utilization", models.TextField(blank=True, null=True)),
            ],
            bases=("reports.report",),
        ),
        migrations.CreateModel(
            name="PublicationReport",
            fields=[
                (
                    "report_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reports.report",
                    ),
                ),
                ("publication_title", models.CharField(max_length=255)),
                (
                    "publication_type",
                    models.CharField(
                        choices=[
                            (
                                "PEER_REVIEWED_JOURNAL_ARTICLE",
                                "Peer Reviewed Journal Article",
                            ),
                            ("BOOK", "Book"),
                            (
                                "EDITED_OR_PEER_REVIEWED_BOOK_CHAPTER",
                                "Edited or Peer Reviewed Book Chapter",
                            ),
                            (
                                "PEER_REVIEWED_CONFERENCE_PAPER_PUBLICATION",
                                "Peer Reviewed Conference Paper Publication",
                            ),
                            ("OTHER", "Other"),
                        ],
                        max_length=42,
                    ),
                ),
                (
                    "author_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("publication_date", models.DateField()),
                ("publisher_name", models.CharField(max_length=255)),
                (
                    "publisher_type",
                    models.CharField(
                        choices=[
                            ("COMMERCIAL", "Commercial"),
                            (
                                "LEARNED_SOCIETY_AND_ASSOCIATION",
                                "Learned Society and Association",
                            ),
                            ("UNIVERSITY_PRESS", "University Press"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "publisher_location",
                    models.CharField(
                        choices=[
                            ("LOCAL", "Local"),
                            ("INTERNATIONAL", "International"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "editor_names",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("volume_number", models.CharField(max_length=255)),
                ("issue_number", models.CharField(max_length=255)),
                ("doi_or_url", models.URLField()),
                ("isbn_or_issn", models.CharField(max_length=255)),
                ("number_of_citations", models.IntegerField()),
            ],
            bases=("reports.report",),
        ),
        migrations.CreateModel(
            name="ResearchReport",
            fields=[
                (
                    "report_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reports.report",
                    ),
                ),
                ("timeframe", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "name_of_researchers",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("source_of_funding", models.CharField(max_length=255)),
            ],
            bases=("reports.report",),
        ),
        migrations.CreateModel(
            name="TrainingReport",
            fields=[
                (
                    "report_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reports.report",
                    ),
                ),
                ("activity_type", models.CharField(max_length=100)),
                ("course_or_service_title", models.CharField(max_length=255)),
                ("venue", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("schedule_special_notes", models.TextField(blank=True, null=True)),
                (
                    "hours_required_to_complete",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "number_of_trainees_served",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "source_of_funding",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            bases=("reports.report",),
        ),
        migrations.CreateModel(
            name="FileUploads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="uploads/")),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="file_uploads",
                        to="reports.report",
                    ),
                ),
            ],
        ),
    ]
