# Generated by Django 5.1.6 on 2025-04-17 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="extensionreport",
            name="report_id",
        ),
        migrations.RemoveField(
            model_name="otherresearchreport",
            name="report_id",
        ),
        migrations.RemoveField(
            model_name="othersreport",
            name="report_id",
        ),
        migrations.RemoveField(
            model_name="paperpresentationreport",
            name="report_id",
        ),
        migrations.RemoveField(
            model_name="partnershipreport",
            name="report_id",
        ),
        migrations.RemoveField(
            model_name="patentreport",
            name="report_id",
        ),
        migrations.RemoveField(
            model_name="publicationreport",
            name="report_id",
        ),
        migrations.RemoveField(
            model_name="trainingreport",
            name="report_id",
        ),
        migrations.AddField(
            model_name="researchreport",
            name="file",
            field=models.FileField(default=1, upload_to=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="researchreport",
            name="report_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report",
                to="reports.report",
            ),
        ),
    ]
