# Generated by Django 5.1.6 on 2025-04-19 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_supportingdocument_delete_fileuploads"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportingdocument",
            name="owner",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supporting_document",
                to="reports.report",
            ),
        ),
    ]
