# Generated by Django 5.1.6 on 2025-04-20 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_alter_supportingdocument_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="otherresearchreport",
            name="output_title",
        ),
        migrations.RemoveField(
            model_name="publicationreport",
            name="publication_title",
        ),
    ]
