# Generated by Django 5.1.4 on 2025-03-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
