# Generated by Django 5.1.4 on 2025-04-06 10:03

from django.db import migrations

def create_initial_roles_and_permissions(apps, schema_editor):
    Role = apps.get_model('user', 'Role')
    Permission = apps.get_model('user', 'Permission')
    RolePermission = apps.get_model('user', 'RolePermission')

    # Create permissions
    view_perm = Permission.objects.create(name="Can view", code_name="can_view")
    edit_perm = Permission.objects.create(name="Can edit", code_name="can_edit")
    delete_perm = Permission.objects.create(name="Can delete", code_name="can_delete")

    # Create roles
    admin_role = Role.objects.create(name="Admin", code="AD")
    manager_role = Role.objects.create(name="Manager", code="MG", parent=admin_role)
    staff_role = Role.objects.create(name="Staff", code="ST", parent=manager_role)

    # Assign permissions
    RolePermission.objects.create(role=staff_role, permission=view_perm)
    RolePermission.objects.create(role=manager_role, permission=edit_perm)
    RolePermission.objects.create(role=admin_role, permission=delete_perm)

def reverse_func(apps, schema_editor):
    Role = apps.get_model('user', 'Role')
    Permission = apps.get_model('user', 'Permission')
    RolePermission = apps.get_model('user', 'RolePermission')

    RolePermission.objects.all().delete()
    Role.objects.all().delete()
    Permission.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_role_permissions_alter_rolepermission_role'),
    ]

    operations = [
        migrations.RunPython(create_initial_roles_and_permissions, reverse_func),
    ]
