# Generated by Django 5.1.4 on 2025-03-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='az', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
