# Generated by Django 5.1.6 on 2025-04-24 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports_v2", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponseDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="form_documents/")),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supporting_documents",
                        to="reports_v2.response",
                    ),
                ),
            ],
        ),
    ]
