# Generated by Django 5.1.6 on 2025-04-24 12:13

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports_v2", "0002_responsedocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="valid_date_range",
            field=django.contrib.postgres.fields.ranges.DateRangeField(
                blank=True, null=True
            ),
        ),
    ]
